project_id = "rvmpjcargszbnkjynxxu"

[functions.docusign-auth]
verify_jwt = false

[functions.docusign-callback]
verify_jwt = false

[functions.docusign-send]
verify_jwt = false

[functions.docusign-webhook]
verify_jwt = false
