// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-stable-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var get_stable_info_default = defineTool({
  name: "get_stable_info",
  title: "Get Swan Hill Stables info",
  description: "Returns basic public info about Swan Hill Stables: address, phone, email, hours, and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Swan Hill Stables",
      tagline: "Premium horse boarding, expert riding lessons, and a welcoming equestrian community.",
      address: "3550 Skipper Rd, Northport, Alabama",
      phone: "+1 (617) 513-7262",
      email: "stables@swanhillstables.com",
      website: "https://swanhillstables.com",
      social: {
        instagram: "https://www.instagram.com/swan.hill.stables"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List Swan Hill Stables services",
  description: "Lists the services Swan Hill Stables offers with a short summary and starting price. Use `category` to filter to just boarding or lessons.",
  inputSchema: {
    category: z2.enum(["boarding", "lessons", "all"]).default("all").describe("Which service category to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const services = [
      {
        category: "boarding",
        name: "Full-Service Board",
        startingPriceUSD: 800,
        summary: "Stall board with daily turnout, feed, hay, stall cleaning, and blanket changes."
      },
      {
        category: "boarding",
        name: "Pasture Board",
        startingPriceUSD: 500,
        summary: "24/7 pasture living with shelter, hay, and daily wellness checks."
      },
      {
        category: "lessons",
        name: "Private Riding Lesson",
        startingPriceUSD: 50,
        summary: "One-on-one instruction for all levels. Payment via Venmo @swanhillstables."
      }
    ];
    const filtered = category === "all" ? services : services.filter((s) => s.category === category);
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { services: filtered }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "swan-hill-stables-mcp",
  title: "Swan Hill Stables",
  version: "0.1.0",
  instructions: "Tools for Swan Hill Stables \u2014 a premium horse boarding and riding lesson facility. Use `get_stable_info` for contact/address details, and `list_services` for boarding and lesson offerings with starting prices.",
  tools: [get_stable_info_default, list_services_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
